CXXFLAGS = --std=c++17


test: Test.cpp
	$(CXX) $(CXXFLAGS) -o test Test.cpp
	
test2: Test2.cpp
	$(CXX) $(CXXFLAGS) -o test2 Test2.cpp
	@printf "Now type './test', './test2', or exicute the result\n\n"

	
 


	
